language: ruby
rvm:
  - 2.2

before_install:
  - 'git checkout -B $TRAVIS_BRANCH' # Reconcile detached HEAD
  - 'npm install -g bower grunt-cli'
  - 'gem install jekyll -v 3.1.6'

script:
  - 'npm install'
  - 'bower install'
  - 'grunt'

after_success:
  - sh -x ./scripts/setup-git-env.sh
  - sh -x ./scripts/publish.sh
  - sh -x ./scripts/publish-ghpages.sh

deploy:
  provider: openshift
  user: "$OPENSHIFT_USER"
  password: "$OPENSHIFT_PWD"
  domain: "patternfly"
  app: v2
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_REPO_SLUG = "patternfly/patternfly-org"
