language: node_js
node_js:
- '8'
sudo: required
cache: yarn
notifications:
  email: false
git:
  depth: 1
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
- export PATH=$HOME/.yarn/bin:$PATH
- sudo apt-get install -y python3-pip
- pip3 install --user awscli
script:
- yarn build
- bash ./scripts/prepare-deploy.sh
- bash ./scripts/deploy.sh
- if [[ -d out && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then bash ./scripts/deploy.sh; fi;
