language: ruby
rvm:
  - 2.3.1

env:
  global:
  - ENCRYPTION_LABEL: "195bd079f767"
  - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
  - TRIGGER_REPO_SLUG: "patternfly/patternfly-org"
  - TRIGGER_REPO_BRANCH: "master"

before_install:
  - nvm install 4
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g bower grunt-cli
  - npm install git+https://github.com/patternfly/patternfly-eng-release.git

install: true

script:
  - sh -x ./node_modules/patternfly-eng-release/scripts/_build.sh -o

after_success:
  - grunt build
  - npm run publish-travis
